# Bài tập Thực hành Trực quan hóa Dữ liệu

## Dữ liệu 'Data_sale.csv'
`Bộ dữ liệu bao gồm thông tin về doanh số bán hàng, số lượng khách hàng, sản phẩm, và vùng địa lý  `
- Date: Ngày cuối mỗi tháng từ tháng 1 đến tháng 10 năm 2023.
- Region: Vùng địa lý (Bắc, Nam, Đông, Tây).
- Product: Loại sản phẩm (A, B, C, D).
- Sales: Doanh số bán hàng (giá trị định lượng).
- Customers: Số lượng khách hàng.
- Profit: Lợi nhuận thu được từ doanh số.

## Bài tập 1: Biểu đồ Scatter Plot
Hãy vẽ biểu đồ scatter plot thể hiện mối quan hệ giữa số lượng khách hàng và doanh số:

### Yêu cầu:
1. Trục x: Số lượng khách hàng (Customers)
2. Trục y: Doanh số (Sales)  
4. Thêm:
    - Tiêu đề biểu đồ
    - Nhãn trục x, y
    - Chú thích (legend) cho các vùng
5. Nhận xét đưa ra insights

## Bài tập 2: Biểu đồ Box Plot
Tạo box plot so sánh phân phối doanh số giữa các sản phẩm:

### Yêu cầu:
1. Trục x: Sản phẩm (Product)
2. Trục y: Doanh số (Sales)
3. Sử dụng màu sắc khác nhau cho mỗi sản phẩm
4. Thêm tiêu đề phù hợp cho biểu đồ
5. Nhận xét đưa ra insights

## Bài tập 3: Biểu đồ Tròn (Pie Chart)
Vẽ biểu đồ tròn thể hiện tỷ trọng doanh số của từng vùng:

### Yêu cầu:
1. Tính tổng doanh số theo vùng
2. Tạo pie chart với:
    - Các phần được tô màu khác nhau
    - Nhãn phần trăm cho mỗi phần
3. Thêm tiêu đề cho biểu đồ
4. Nhận xét đưa ra insights

## Hướng dẫn:
1. Import các thư viện cần thiết:
```python
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
```

2. Đọc dữ liệu:
```python
df = pd.read_csv('Data_sale.csv')
```

3. Sử dụng các hàm vẽ biểu đồ từ matplotlib hoặc seaborn để hoàn thành bài tập

### ***Buổi online chị sẽ chữa và giải thích các công thức toán thường gặp trong các biểu đồ. Các bạn tham gia đầy đủ nhé!!!***

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('Data_sale.csv')
df

          Date Region Product  Sales  Customers  Profit
0   2023-01-01  North       A    733         77      36
1   2023-01-02   West       B    184         92     172
2   2023-01-03  South       B    303         56     177
3   2023-01-04  North       B    424         30     169
4   2023-01-05   West       D    874         91     130
5   2023-01-06   West       A    147         60      45
6   2023-01-07   West       D    739         37     141
7   2023-01-08   West       C    231         24     138
8   2023-01-09  South       A    968         51     100
9   2023-01-10   West       D    280         68     103
10  2023-01-11  South       D    946         75     181
11  2023-01-12   East       C    243         46     124
12  2023-01-13  North       D    760         20     180
13  2023-01-14   West       C    327         96     141
14  2023-01-15   East       D    891         53      90
15  2023-01-16  North       A    819         21      51
16  2023-01-17  North       C    473         12      33
17  2023-01-18  North       A   1000         61      91
18  2023-01-19   East       A    660         90     172
19  2023-01-20  South       A    405         42      99
20  2023-01-21   East       B    681         64      61
21  2023-01-22   West       B    269         10      38
22  2023-01-23   West       C    775         48      60
23  2023-01-24   East       A    548         29      31
24  2023-01-25  North       A    195         56     186
25  2023-01-26  South       B    297         52     131
26  2023-01-27  South       D    706         66     113
27  2023-01-28  South       A    356         70     100
28  2023-01-29  South       B    981         87     138
29  2023-01-30  North       C    790         40      64
30  2023-01-31  South       C    392         34     145
31  2023-02-01  North       D    916         12      44
32  2023-02-02   West       A    961         13      87
33  2023-02-03  North       B    487         23      23
34  2023-02-04   West       B    710         50      55
35  2023-02-05  South       D    654         82      63
36  2023-02-06   East       B    468         29      52
37  2023-02-07   West       B    301         82      31
38  2023-02-08   West       D    483         36     124
39  2023-02-09  North       C    612         76     158
40  2023-02-10   East       D    470         62     185
41  2023-02-11   West       D    655         77     145
42  2023-02-12  North       C    483         71     176
43  2023-02-13  South       C    123         24     131
44  2023-02-14   West       D    799         14      22
45  2023-02-15  South       A    230         77      47
46  2023-02-16   West       C    477         21     171
47  2023-02-17   West       D    198         96      73
48  2023-02-18   East       B    674         87      71
49  2023-02-19   West       A    834         85     194